#! /bin/bash

usage () {
      echo "$0: a small wrapper to generate a rpm."
      echo "Usage: $0 -d"
      echo "Options:"
      echo " -d: -doit ;-)"
}

if [ "$1" != "-d" ]; then
   usage
   exit 1
fi

buildroot=$(dirname $(readlink -f "$0"))
mkdir -p ${buildroot}/{RPMS,BUILD}
rpmbuild --verbose \
    --define "_sourcedir ${buildroot}" \
    --define "_topdir ${buildroot}" \
    -bb "${buildroot}/spec"

